apiVersion: apps/v1
kind: Deployment
metadata:
  name: mev-bot
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: arb-bot
        image: mev-bot:4.0
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
        env:
        - name: ETH_RPC_WS_URL
          valueFrom:
            secretKeyRef:
              name: rpc-secrets
              key: eth-ws-url
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: wallet-secrets
              key: private-key
---
# Auto-scaling config
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mev-bot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mev-bot
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80